[package]
name = "banso"
description = "Bayesian network solver using No U-Turn Sampler"
version = "0.1.0"
edition = "2021"
authors = ["Oliver Ruebenacker <oliverr@broadinstitute.org>"]
readme = "README.md"
repository = "https://github.com/broadinstitute/banso"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nuts-rs = "0.4.1"
